# Configure MSW api

# MSW api key
api_key : '1'

# Spots you would like forecast data for, {name of spot:msw spot id}
spots : {'Thurso':47,'SuperTubos':196}

# Days you would like to surf on
days : ['Friday','Saturday','Sunday']