# Configure MSW api

# MSW api key
api_key : '1'

# Spots you would like forecast data for, {name of spot:msw spot id}
spots : {'Thurso':47,'Supertubos':196,'Los Lobos':925,'La Graviere':61,
         'Coxos':4344,'Pico da Mota':4349,'Zavial':4324,'Mundaka':169,
         'Porthleven':1253,'Anchor Point':905,'Safi':251,'Boilers':252,
         'Mullaghmore':1505}

# Days you would like to surf on
days : ['Friday','Saturday','Sunday']